export default {
  API: "api",
  AUTH: "auth",
  TESTS: "tests",
  USERS: "users",
  PRODUCTS: "products",
  DELIVERY: "delivery",
  SERVICES: "services",
  APPOINTMENTS: "appointments",
  TRANSACTIONS: "transactions",
  BRANDS: "brands",
  COMMENTS: "comments",
  FEEDBACKS: "feedbacks",
  INGREDIENTS: "ingredients",
  OPTIONS: "options",
  SCHEDULES: "schedules",
  TIMES: "times",
  DELIVERY: "delivery",
  EXCLUSIONS: "exclusions",
  MONTHS: "months",
};
